config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  authenticate :admin_user do
    mount Sidekiq::Web => '/sidekiq'
  end

  get 'search', to: 'search#index'
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users
  resources :products
  resources :categories
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root 'products#index'

  # Defines the cart path route
  get 'cart', to: 'carts#show', as: :cart
  resources :line_items, only: %i[create destroy update]
  # post 'line_items/:id/increase_quantity', to: 'line_items#increase_quantity', as: 'line_item_increase'
  # post 'line_items/:id/decrease_quantity', to: 'line_items#decrease_quantity', as: 'line_item_decrease'
  resources :orders, only: %i[index create show destroy]
  patch 'orders/:id/update', to: 'orders#update', as: 'order_paid'
end

app/models/product.rb
# == Schema Information
#
# Table name: products
#
#  id          :bigint           not null, primary key
#  description :text
#  name        :string           not null
#  price       :decimal(10, 2)
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#
class Product < ApplicationRecord
  validates :name, presence: true
  validates :price, presence: true, numericality: { greater_than_or_equal_to: 0 }

  has_many :product_categories, dependent: :destroy
  has_many :categories, through: :product_categories

  has_many :line_items, dependent: :destroy

  accepts_nested_attributes_for :product_categories, allow_destroy: true

  has_one_attached :image do |attachable|
    attachable.variant :thumb, resize_to_limit: [100, 100]
    attachable.variant :main, resize_and_pad: [340, 340]
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: %i[show]

  def index
    @products = Product.all
    MonthWinnerJob.perform_at(10.seconds.from_now)
  end

  def show
    @categories = @product.categories
  end

  private

  def set_product
    @product = Product.find(params[:id])
  end

  def product_params
    params.require(:product).permit(:name, :description, :price, :image)
  end
end

app/views/products/_products.html.erb
<div class="col" %>
  <div class="card shadow-sm">
    <div class="album py-5 bg-light">
      <div class="container">
        <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
            <% @products.each do |product| %>
              <div class="col">
                <div class="card shadow-sm" style="width: 20rem;">
                  <% if product.image.attached? %>
                    <%= image_tag product.image.variant(:main), class: 'class="bd-placeholder-img card-img-top', height: 225, alt: product.name %>
                    <% else %>
                    <%= image_tag("no_image_item.jpeg", class: 'class="bd-placeholder-img card-img-top', height: 225, alt: 'Photo coming soon') %>
                  <% end %>
                  <div class="card-body">
                    <p class="card-text"><%= link_to product.name, product %></p>
                    <div class="d-flex justify-content-between align-items-center">
                      <div class="btn-group">
                      <%if user_signed_in? %>
                        <%= button_to 'Add to cart', line_items_path(product_id: product.id), class:"btn btn-sm btn-outline-secondary" %>
                      <% else %>
                        <%= link_to'Add to cart', new_user_session_path, class:"btn btn-sm btn-outline-secondary" %>
                      <% end %>
                      </div>
                      <small class="text-muted"><%= number_to_currency(product.price) %></small>
                    </div>
                  </div>
                </div>
              </div>
            <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/products/index.html.erb
<%= render "products" %>

app/views/products/show.html.erb
<div class="container col-xxl-8 px-4 py-5">
  <div class="row flex-lg-row-reverse align-items-center g-5">
    <div class="col-lg-6 mg-0 mt-0">
      <h1 class="display-5 fw-bold lh-1 mb-3"><%= @product.name %></h1>
        <div class='lead'>
          <p><%= @product.description %></p>
          <h6>Categories:</h6>
          <% @categories.each do |category|%>
          <h6> <%= category.title %></h6>
          <% end %>
          <p><%= number_to_currency(@product.price) %></p>
        </div>
      <div class="d-grid gap-2 d-md-flex justify-content-md-start">
        <%if user_signed_in? %>
            <%= button_to 'Buy', line_items_path(product_id: @product.id), class:"btn btn-primary btn-lg px-4 me-md-2" %>
          <% else %>
            <%= link_to 'Buy', new_user_session_path, class:"btn btn-primary btn-lg px-4 me-md-2" %>
        <% end %>
        <%if user_signed_in? %>
            <%= button_to 'Add to cart', line_items_path(product_id: @product.id), class:"btn btn-outline-secondary btn-lg px-4" %>
          <% else %>
            <%= link_to 'Add to cart', new_user_session_path, class:"btn btn-outline-secondary btn-lg px-4" %>
        <% end %>
      </div>
    </div>
    <div style="margin:0" class="col-10 col-sm-8 col-lg-6">
    <% if @product.image.attached? %>
      <%= image_tag @product.image.variant(:main), class: 'class="bd-placeholder-img card-img-top', alt: @product.name %>
      <% else %>
      <%= image_tag("no_image_item.jpeg", class: 'class="bd-placeholder-img card-img-top', alt: 'Photo coming soon') %>
    <% end %>
    </div>
  </div>
</div>